server:
  port: 3001
spring:
  application:
    name: gateway-demo
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
#      routes:
#        - id: cloud
#          uri: lb://EUREKA-CLIENT
#          predicates:
#            - Path=/eureka-client/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://111.230.134.49:1001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: trace
    org.springframework.web.reactive: trace
    org.springframework.boot.autoconfigure.web: trace
    reactor.ipc.netty: trace
